kind: pipeline
name: default

steps:
  - name: ping
    image: mongo:4.4
    commands:
      - sleep 5
      - mongo --host mongo --eval "db.version()"


  - name: test
    image: python:3.7-buster
    commands:
      - export VT_DB_CONNECTION_STRING="mongodb://mongo:27017"
      - export VT_REDIS_CONNECTION_STRING="redis://redis:6379/1"
      - pip install tox
      - tox

  - name: coverage
    image: python:3.8-alpine
    environment:
      CODACY_PROJECT_TOKEN:
        from_secret: CODACY_PROJECT_TOKEN
    commands:
      - apk add git
      - pip install codacy-coverage
      - python-codacy-coverage -r coverage.xml -c $DRONE_COMMIT_SHA -d $PWD
    when:
      event:
        - push

services:
  - name: mongo
    image: mongo:4.4
    command: [--nojournal]
    ports:
      - 27017

  - name: redis
    image: redis:6.0.8
    ports:
      - 6379
