kind: pipeline
name: default

steps:
  - name: ping
    image: mongo:4.4
    commands:
      - sleep 5
      - mongo --host mongo --eval "db.version()"


  - name: test
    image: virtool/external-tools:0.1.2
    commands:
      - export DATABASE_CONNECTION_URL="mongodb://mongo:27017"
      - export VIRTOOL_REDIS_ADDRESS="redis://redis:6379/1"
      - pip install dataclasses
      - pip install .
      - pip install pytest pytest-aiohttp pytest-asyncio pytest-coverage
      - pytest -x --cov --cov-report xml

  - name: coverage
    image: python:3.8-alpine
    environment:
      CODACY_PROJECT_TOKEN:
        from_secret: CODACY_PROJECT_TOKEN
    commands:
      - apk add git
      - pip install codacy-coverage
      - python-codacy-coverage -r coverage.xml -c $DRONE_COMMIT_SHA -d $PWD
    when:
      event:
        - push

services:
  - name: mongo
    image: mongo:4.4
    command: [--nojournal]
    ports:
      - 27017

  - name: redis
    image: redis:6.0.8
    ports:
      - 6379
