[tool.poetry]
name = "virtool-workflow"
version = "0.4.0"
description = "A framework for developing bioinformatics workflows for Virtool."
authors = ["Ian Boyes", "Blake Smith"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/virtool/virtool-workflow"
classifiers = [
    "Topic :: Software Development :: Libraries",
    "Programming Language:: Python:: 3.9",
]
packages = [
    { include = "virtool_workflow" },
    { include = "virtool_workflow_runtime" },
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
motor = "2.3.0"
aiohttp = "3.7.3"
aioredis = "1.3.1"
aiofiles = "^0.6.0"
virtool-core = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
pytest-xdist = "^2.2.0"
pytest-cov = "^2.11.1"
pytest-aiohttp = "0.3.0"
tox-docker = "^2.0.0"

[tool.poetry.scripts]
workflow = "virtool_workflow.cli:cli_main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
