version: "3.1"
services:
    integration_test_workflow:
        image: virtool/integration_test_workflow
        depends_on:
            - job-api

    job-api:
        image: virtool/jobs-api
        depends_on: 
            - mongo
            - redis
            - postgres
            - pgadmin4
        command: > 
            --db-connection-string="mongodb://mongo:27017"
            --postgres-connection-string="postgresql+asyncpg://virtool:virtool@postgres/virtool"
            --redis-connection-string="redis://redis:6379"
            jobsAPI

    mongo:
        image: mongo:4.4
        ports:
          - "27017:27017"
        volumes:
          - vt_mongo_data:/data/db
        logging:
          driver: none

    redis:
        image: redis:6.0
        ports:
          - "6379:6379"
        volumes:
          - vt_redis_data:/data
        logging:
          driver: none

    postgres:
        image: postgres:13.1
        ports:
          - "5432:5432"
        restart: always
        environment:
          POSTGRES_USER: virtool
          POSTGRES_PASSWORD: virtool
        volumes:
          - vt_postgres_data:/var/lib/postgresql/data
        logging:
          driver: none

    pgadmin4:
        image: dpage/pgadmin4:4.29
        environment:
          PGADMIN_DEFAULT_EMAIL: dev@virtool.ca
          PGADMIN_DEFAULT_PASSWORD: virtool
          PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
          PGADMIN_LISTEN_PORT: 5050
        ports:
          - "5050:5050"
        volumes:
          - vt_pgadmin4_data:/var/lib/pgadmin4/data
        depends_on: [ postgres ]
        logging:
          driver: none

volumes:
  vt_mongo_data:
  vt_redis_data:
  vt_postgres_data:
  vt_pgadmin4_data:


