name: Merge Master Back To Develop
on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        branches:
            - master

jobs:
    merge-back:
        if: github.event.pull_request.merged == true || {{$GITHUB_EVENT_NAME}} == "workflow_dispatch"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                ref: develop

          - name: merge
            run: |
                git fetch
                git merge master
                git push

