name: Docker Build

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "release/*"
      - "master"

  workflow_dispatch:

jobs:

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Container
        run: docker build -t virtool/workflow .
