name: Release Workflow Docker Image

on: [ release, workflow_dispatch ]

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          file: $GITHUB_WORKSPACE/docker/Dockerfile
          repository: virtool/workflow
          tag_with_ref: true

      - name: Update README on Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: virtool/workflow
          readme-filepath: $GITHUB_WORKSPACE/docker/README.md

