name: Release Workflow Docker Image

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version Number
        id: get_version
        run: | 
            pip install poetry
            echo "##[set-output name=version;]$(poetry version | cut -f2 -d' ')"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: virtool/workflow:${{ steps.tags.outputs.TAG }}

      - name: Update README on Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: virtool/workflow
          readme-filepath: ./docker/README.md

