name: Enforce Changelog

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "release/*"
      - "master"

jobs:
    changelog:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: dangoslen/changelog-enforcer@v2
          with:
            changeLogPath: 'CHANGELOG.md'
            skipLabels: 'nochangelog'
