name: Poetry Check

on:
  pull_request:
    branches:
      - "release/*"
      - "master"

  workflow_dispatch:

jobs:

  pypi-check:
    runs-on: ubuntu-latest

    container: python:3.8

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry

      - name: Poetry Build
        run: |
            poetry check
            poetry build

      - name: Poetry Publish Dry Run
        run: >-
            poetry publish
            -u ${{ secrets.PYPI_USERNAME }} 
            -p ${{ secrets.PYPI_TOKEN }}
            --dry-run
