name: PyPi Publish

on:
  release:
    types: [ published ]

  workflow_run:
    workflows:
      - Create Github Release
    branches:
      - master
    types:
      - completed 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-buster

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry

      - name: Prepare Distribution
        run: poetry build

      - name: Deploy To PyPi
        run: poetry publish -r ${{ secrets.PYPI_REPOSITORY }} -u ${{ secrets.PYPI_USERNAME }} -p {{PYPI_TOKEN}}
