# Run test suite using tox.
name: Tests

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "master"

jobs:

  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-buster

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry

      - name: Install tox
        run: |
          pip install tox
          pip install tox-docker

      - name: Install Bowtie2
        run: |
          wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.2/bowtie2-2.3.2-legacy-linux-x86_64.zip
          unzip bowtie2-2.3.2-legacy-linux-x86_64.zip
          cp bowtie2-2.3.2-legacy/bowtie2* /usr/local/bin

      - name: Install HMMER
        run: |
          wget http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
          tar -xvf hmmer-3.3.2.tar.gz
          cd hmmer-3.3.2
          ./configure --prefix $GITHUB_WORKSPACE/hmmer
          make
          make install
          cd ..
          ln -s $GITHUB_WORKSPACE/hmmer/bin/hmm* /usr/local/bin

      - name: Run tox
        run: tox -- --log-cli-level=INFO

      - name: Upload Coverage Report As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: $GITHUB_WORKSPACE/coverage.xml
