# Run test suite using tox.
name: CI

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "master"

jobs:

  test:
    runs-on: ubuntu-latest
   
    container:
      image: python:3.9-buster
    
    services:
      redis: 
        image: redis:6.0
      mongo:
        image: mongo:4.4
        
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install tox
        
      - name: Run tox
        run: tox
        env:
          VT_DB_CONNECTION_STRING: mongodb://mongo:27017
          VT_REDIS_CONNECTION_STRING: redis://redis:6379/1

      - name: Upload Coverage Report As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

  codacy-coverage-reporter:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    name: Update Coverage Report
    steps:
      - uses: actions/checkout@master

      - name: Download Latest Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: $GITHUB_WORKSPACE/coverage.xml

