# Run test suite using tox.

name: CI

on:
  pull_request:
    branches:
      - "*"
        
jobs:

  test:
    runs-on: ubuntu-latest
   
    container:
      image: python:3.7-buster
    
    services:
      redis: 
        image: redis
      mongo:
        image: mongo
        
    steps:
      - uses: actions/checkout@v2

      - name: install tox
        run: pip install tox
        
      - name: setup environment
        run: |
          export VT_DB_CONNECTION_STRING="mongodb://mongo:27017"
          export VT_REDIS_CONNECTION_STRING="redis://redis:6379/1"
        
      - name: run test suite
        run: tox
