# Run test suite using tox.
name: Tests

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "master"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11


      - name: Run Tests Using Docker Compose
        run: |
          cd tests
          docker-compose up --build --exit-code-from pytest

      - name: Print Files
        run: >-
          ls -la -R &&
          ls -la tests &&
          echo "$GITHUB_WORKSPACE"

      - name: Upload Coverage Report As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: ./tests/coverage/coverage.xml

      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: test/tests/coverage/coverage.xml
